### ISSUE TITLE
Cannot connect to launchdarkly while using this library

### ISSUE THREAD

**Issue by shankurmahajan** [TrueCar/react-launch-darkly#68] opened 2018-06-29 20:02 UTC
I keep getting this message on connecting to launchdarkly via react-launch-darkly. I am using the correct client key and user key is just email. May I know where I am going wrong.

![image](https://user-images.githubusercontent.com/12533958/42112307-fabd21dc-7bac-11e8-92f7-b6bcfdae97ac.png)

This is the code I am using 
```
    <LaunchDarkly
      clientId="**************"
      user={{ key: '**********'}}
    >
      {props.children}
    </LaunchDarkly>
```

**Comment by shankurmahajan** [comment] 2018-06-29 21:39
@jacobmoretti please look into it

**Comment by shankurmahajan** [comment] 2018-06-29 22:07
@sethbattin tagging

**Comment by shankurmahajan** [comment] 2018-06-29 22:18
tagging @threehams @bearMountain

**Comment by sethbattin** [comment] 2018-06-30 02:29
@shankurmahajan, I think the error message you are seeing describes the problem, which is that `this.context` is undefined.  May I ask you what version of react you are using?  Also can you describe the component hierarchy immediately surrounding your usage of `<FeatureFlag>`?  Obviously that component needs to reside within the `<LaunchDarkly>` wrapper, so please confirm that just to be thorough.

My first guess is that you are the first person to report a problem with this library's version of `react-broadcast` and `react@16.3`.  That is, we do not have up-to-date context handling.  I'm speculating, so that theory would need to be confirmed with some research and/or experimenting.  If you are able to confirm or deny that a dependency update is effective at resolving this, by all means please submit a patch.

Barring that, I sense that you might not get a response as urgently as your 4-way tagging suggests you would like.  It is Friday evening, afterall.  But I should be able to give it some attention within the next week.

**Comment by sethbattin** [comment] 2018-06-30 02:34
Hm, a quick look at the docs means my theory is certainly wrong: https://reactjs.org/docs/context.html#legacy-api
> React previously shipped with an experimental context API. The old API will be supported in all 16.x releases...
So that can't (shouldn't) be the problem.

I guess, all the more reason to describe your usage in more detail.

**Comment by sethbattin** [comment] 2018-07-02 14:17
Ah, so it looks like you missed this precondition:
> ...that component (FeatureFlag) needs to reside within the <LaunchDarkly> wrapper...

It looks like you've appended `LaunchDarkly` as a sibling of the entirety of your application.  That means that the rest of your app has no access to it.  It needs to be a parent of usages of `FeatureFlag`; the same pattern as `Provider`, `ConnectedRouter`, and `MuiThemeProvider`.  That is necessary for the subscribe/broadcast mechanism to work.

Side note: in your example code, you are rendering the wrapper with `props.children`, which doesn't make sense because you pass this component directly to `ReactDOM.render(<App />...`, so it doesn't have any children and never will.  Possibly you edited this code in order to paste it here, and introduced that as a bug?  That pattern appears in our readme which describes using the component as a high-level application wrapper, but again that only makes sense if it's part of a hierarchy with child components.  This section of the react docs describes correct usage of `children`: https://reactjs.org/docs/composition-vs-inheritance.html#containment

**Comment by jacobmoretti** [comment] 2018-07-18 16:24
@shankurmahajan Did @sethbattin comments resolve your issue?

**Comment by jacobmoretti** [comment] 2018-09-24 23:19
Closing issue for lack of activity.

**Closed by jacobmoretti** 2018-09-24 23:19 UTC
